# Generated by Django 6.1 on 2026-08-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_adminmfa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
    ]
