# Generated by Django 6.1 on 2026-08-17 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_client_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoLiveStepNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('author', models.CharField(default='Admin User', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golive_notes', to='api.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.golivestepdefinition')),
            ],
            options={
                'db_table': 'golive_step_notes',
                'ordering': ['-id'],
            },
        ),
    ]
