# Generated by Django 4.2.17 on 2026-08-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdocument',
            name='direction',
        ),
    ]
