# Generated by Django 4.2.17 on 2026-08-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_clientdocument_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingStepDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('step_key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'api_offboarding_step_def',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingStepUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=150)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboard_uploads', to='api.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offboardingstepdefinition')),
            ],
            options={
                'db_table': 'api_offboarding_upload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingStepNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboard_notes', to='api.client')),
                ('step_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offboardingstepdefinition')),
            ],
            options={
                'db_table': 'api_offboarding_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientOffboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('step_key', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboard_statuses', to='api.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offboardingstepdefinition')),
            ],
            options={
                'db_table': 'api_client_offboard_status',
                'unique_together': {('client', 'step')},
            },
        ),
    ]
